<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Denis Haine" />


<title>Multiple Bias Modeling</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Multiple Bias Modeling</h1>
<h4 class="author">Denis Haine</h4>



<p>Epidemiologic studies can suffer from more than one bias. Bias
functions in <code>episensr</code> can be applied sequentially to
quantify bias resulting from multiple biases.</p>
<p>Following the example in <a href="https://link.springer.com/book/10.1007/978-3-030-82673-4">Lash et
al.</a>, we can use the study by <a href="https://link.springer.com/article/10.1007/s10549-005-9056-0">Chien
et al.</a>. It is a case-control study looking at the association
between antidepressant use and the occurrence of breast cancer. The
observed OR was 1.2 [0.9–1.6].</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a>chien <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">118</span>, <span class="dv">832</span>, <span class="dv">103</span>, <span class="dv">884</span>),</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>                <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">&quot;BC+&quot;</span>, <span class="st">&quot;BC-&quot;</span>), <span class="fu">c</span>(<span class="st">&quot;AD+&quot;</span>, <span class="st">&quot;AD-&quot;</span>)),</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>                <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">AD+</th>
<th align="right">AD-</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">BC+</td>
<td align="right">118</td>
<td align="right">832</td>
</tr>
<tr class="even">
<td align="left">BC-</td>
<td align="right">103</td>
<td align="right">884</td>
</tr>
</tbody>
</table>
<p>Records on medication use differed between participants, from
pharmacy records and self-reported use, leading to
misclassification:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">library</span>(episensr)</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>seq_bias1 <span class="ot">&lt;-</span> chien <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>    <span class="fu">misclass</span>(., <span class="at">type =</span> <span class="st">&quot;exposure&quot;</span>,</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>             <span class="at">bias_parms =</span> <span class="fu">c</span>(<span class="dv">24</span><span class="sc">/</span>(<span class="dv">24</span><span class="sc">+</span><span class="dv">19</span>), <span class="dv">18</span><span class="sc">/</span>(<span class="dv">18</span><span class="sc">+</span><span class="dv">13</span>), <span class="dv">144</span><span class="sc">/</span>(<span class="dv">144</span><span class="sc">+</span><span class="dv">2</span>), <span class="dv">130</span><span class="sc">/</span>(<span class="dv">130</span><span class="sc">+</span><span class="dv">4</span>)))</span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a>seq_bias1</span></code></pre></div>
<pre><code>## ── Observed data ───────────────────────────────────────────────────────────────</code></pre>
<pre><code>## • Outcome: BC+</code></pre>
<pre><code>## • Comparing: AD+ vs. AD-</code></pre>
<pre><code>## </code></pre>
<pre><code>##     AD+ AD-
## BC+ 118 832
## BC- 103 884
##                                        2.5%     97.5%
## Observed Relative Risk: 1.1012443 0.9646019 1.2572431
##    Observed Odds Ratio: 1.2172330 0.9192874 1.6117443</code></pre>
<pre><code>## ── Bias-adjusted measures ──</code></pre>
<pre><code>##                                                              2.5%    97.5%
## Misclassification Bias Corrected Relative Risk: 1.256946                  
##    Misclassification Bias Corrected Odds Ratio: 1.628058 1.113458 2.380487</code></pre>
<p>Controls and cases also enrolled into the study at different rates.
By storing the result of <code>misclass()</code> in an object named here
<code>seq_bias1</code>, we have access to the various elements returned
by the function (see the <code>help()</code> for a given function to
know what is returned). The bias-adjusted cell frequencies can be
accessed as <code>corr_data</code>.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>seq_bias1<span class="sc">$</span>corr_data</span></code></pre></div>
<pre><code>##          AD+      AD-
## BC+ 192.8332 757.1668
## BC- 133.5114 853.4886</code></pre>
<p>This 2-by-2 table will be used as starting values for the next
sequential bias adjustment, <code>selection()</code>.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>seq_bias2 <span class="ot">&lt;-</span> seq_bias1<span class="sc">$</span>corr_data <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>    <span class="fu">selection</span>(., <span class="at">bias_parms =</span> <span class="fu">c</span>(.<span class="dv">734</span>, .<span class="dv">605</span>, .<span class="dv">816</span>, .<span class="dv">756</span>))</span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>seq_bias2</span></code></pre></div>
<pre><code>## ── Observed data ───────────────────────────────────────────────────────────────</code></pre>
<pre><code>## • Outcome: BC+</code></pre>
<pre><code>## • Comparing: AD+ vs. AD-</code></pre>
<pre><code>## </code></pre>
<pre><code>##          AD+      AD-
## BC+ 192.8332 757.1668
## BC- 133.5114 853.4886
##                                      2.5%    97.5%
## Observed Relative Risk: 1.256946 1.132669 1.394858
##    Observed Odds Ratio: 1.628058 1.278900 2.072541</code></pre>
<pre><code>## ── Bias-adjusted measures ──</code></pre>
<pre><code>##                                                 
## Selection Bias Corrected Relative Risk: 1.172097
##    Selection Bias Corrected Odds Ratio: 1.448430</code></pre>
<p>The adjusted OR is now 1.45 Again, the bias-adjusted cell frequencies
can be used in the next bias analysis, <code>confounders()</code>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a>seq_bias2<span class="sc">$</span>corr_data</span></code></pre></div>
<pre><code>##          AD+      AD-
## BC+ 262.7156 1251.515
## BC- 163.6169 1128.953</code></pre>
<p>The association between antidepressant use and breast cancer was
adjusted for various confounders (race/ethnicity, income, etc.). None of
these confounders were found to change the association by more than 10%.
However, for illustration, we can add the effect of a potential
confounder (e.g. physical activity):</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>seq_bias3 <span class="ot">&lt;-</span> seq_bias2<span class="sc">$</span>corr_data <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a>    <span class="fu">confounders</span>(., <span class="at">type =</span> <span class="st">&quot;OR&quot;</span>, <span class="at">bias_parms =</span> <span class="fu">c</span>(.<span class="dv">8</span>, .<span class="dv">299</span>, .<span class="dv">436</span>))</span>
<span id="cb22-3"><a href="#cb22-3" tabindex="-1"></a>seq_bias3</span></code></pre></div>
<pre><code>## ── Observed data ───────────────────────────────────────────────────────────────</code></pre>
<pre><code>## • Outcome: BC+</code></pre>
<pre><code>## • Comparing: AD+ vs. AD-</code></pre>
<pre><code>## </code></pre>
<pre><code>##           AD+       AD-
## BC+  262.7156 1251.5153
## BC-  163.6169 1128.9532
##                                        2.5%    97.5%
##         Crude Odds Ratio: 1.448430 1.172758 1.788903
## Odds Ratio, Confounder +: 1.406219                  
## Odds Ratio, Confounder -: 1.406219</code></pre>
<pre><code>## ── Bias-adjusted measures ──</code></pre>
<pre><code>##                                        OR due to confounding
## Standardized Morbidity Ratio: 1.406219              1.030018
##              Mantel-Haenszel: 1.406219              1.030018</code></pre>
<p>The serially bias-adjusted OR is 1.406. And the adjusted cells by
confounders, for regular exercise:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a>seq_bias3<span class="sc">$</span>cfder_data</span></code></pre></div>
<pre><code>##          AD+      AD-
## BC+ 66.83851 478.2302
## BC- 48.92144 492.2236</code></pre>
<p>And for no regular exercise:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a>seq_bias3<span class="sc">$</span>nocfder_data</span></code></pre></div>
<pre><code>##          AD+      AD-
## BC+ 195.8771 773.2851
## BC- 114.6954 636.7296</code></pre>
<p>The same process can be realized in a probabilistic framework, as
each <code>probsens()</code>, <code>probsens.sel()</code> and
<code>probsens_conf()</code> provides the adjusted cell frequencies as
A1, B1, C1, D1 in <code>sim_df</code>.</p>
<table>
<thead>
<tr class="header">
<th align="right"></th>
<th align="center">Exposed</th>
<th align="center">Not exposed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">Cases</td>
<td align="center">A1</td>
<td align="center">B1</td>
</tr>
<tr class="even">
<td align="right">Controls</td>
<td align="center">C1</td>
<td align="center">D1</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> chien <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>    <span class="fu">probsens</span>(., <span class="at">type =</span> <span class="st">&quot;exposure&quot;</span>,</span>
<span id="cb34-3"><a href="#cb34-3" tabindex="-1"></a>             <span class="at">seca =</span> <span class="fu">list</span>(<span class="st">&quot;trapezoidal&quot;</span>, <span class="fu">c</span>(.<span class="dv">45</span>, .<span class="dv">5</span>, .<span class="dv">6</span>, .<span class="dv">65</span>)),</span>
<span id="cb34-4"><a href="#cb34-4" tabindex="-1"></a>             <span class="at">seexp =</span> <span class="fu">list</span>(<span class="st">&quot;trapezoidal&quot;</span>, <span class="fu">c</span>(.<span class="dv">4</span>, .<span class="dv">48</span>, .<span class="dv">58</span>, .<span class="dv">63</span>)),</span>
<span id="cb34-5"><a href="#cb34-5" tabindex="-1"></a>             <span class="at">spca =</span> <span class="fu">list</span>(<span class="st">&quot;trapezoidal&quot;</span>, <span class="fu">c</span>(.<span class="dv">95</span>, .<span class="dv">97</span>, .<span class="dv">99</span>, <span class="dv">1</span>)),</span>
<span id="cb34-6"><a href="#cb34-6" tabindex="-1"></a>             <span class="at">spexp =</span> <span class="fu">list</span>(<span class="st">&quot;trapezoidal&quot;</span>, <span class="fu">c</span>(.<span class="dv">96</span>, .<span class="dv">98</span>, .<span class="dv">99</span>, <span class="dv">1</span>)),</span>
<span id="cb34-7"><a href="#cb34-7" tabindex="-1"></a>             <span class="at">corr_se =</span> .<span class="dv">8</span>, <span class="at">corr_sp =</span> .<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## ℹ Calculating observed measures</code></pre>
<pre><code>## ⠙ Assign probability distributions</code></pre>
<pre><code>## ✔ Assign probability distributions [12ms]</code></pre>
<pre><code>## </code></pre>
<pre><code>## ⠙ Simple bias analysis</code></pre>
<pre><code>## ✔ Simple bias analysis [20ms]</code></pre>
<pre><code>## </code></pre>
<pre><code>## ⠙ Incorporating random error</code></pre>
<pre><code>## ✔ Incorporating random error [29ms]</code></pre>
<pre><code>## </code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" tabindex="-1"></a><span class="fu">str</span>(mod1)</span></code></pre></div>
<pre><code>## List of 7
##  $ obs_data    : num [1:2, 1:2] 118 103 832 884
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:2] &quot;BC+&quot; &quot;BC-&quot;
##   .. ..$ : chr [1:2] &quot;AD+&quot; &quot;AD-&quot;
##  $ obs_measures: num [1:2, 1:3] 1.101 1.217 0.965 0.919 1.257 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:2] &quot; Observed Relative Risk:&quot; &quot;    Observed Odds Ratio:&quot;
##   .. ..$ : chr [1:3] &quot; &quot; &quot;2.5%&quot; &quot;97.5%&quot;
##  $ adj_measures: num [1:4, 1:3] 1.073 1.073 1.151 1.152 0.962 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:4] &quot;Relative Risk -- systematic error:&quot; &quot;                      total error:&quot; &quot;   Odds Ratio -- systematic error:&quot; &quot;                      total error:&quot;
##   .. ..$ : chr [1:3] &quot;Median&quot; &quot;p2.5&quot; &quot;p97.5&quot;
##  $ sim_df      :&#39;data.frame&#39;:    1000 obs. of  27 variables:
##   ..$ seca   : num [1:1000] 0.577 0.497 0.535 0.531 0.6 ...
##   ..$ seexp  : num [1:1000] 0.57 0.452 0.479 0.493 0.608 ...
##   ..$ spca   : num [1:1000] 0.965 0.96 0.983 0.979 0.97 ...
##   ..$ spexp  : num [1:1000] 0.983 0.967 0.989 0.99 0.97 ...
##   ..$ A1     : num [1:1000] 157 174 197 192 157 ...
##   ..$ B1     : num [1:1000] 793 776 753 758 793 ...
##   ..$ C1     : num [1:1000] 156 168 197 193 127 ...
##   ..$ D1     : num [1:1000] 831 819 790 794 860 ...
##   ..$ prevca : num [1:1000] 0.171 0.178 0.196 0.174 0.166 ...
##   ..$ prevexp: num [1:1000] 0.182 0.17 0.19 0.187 0.116 ...
##   ..$ ppvca  : num [1:1000] 0.775 0.727 0.887 0.843 0.801 ...
##   ..$ ppvexp : num [1:1000] 0.881 0.739 0.909 0.921 0.726 ...
##   ..$ npvca  : num [1:1000] 0.917 0.898 0.897 0.909 0.924 ...
##   ..$ npvexp : num [1:1000] 0.911 0.896 0.89 0.895 0.949 ...
##   ..$ ab     : num [1:1000] 170 177 184 190 158 169 195 180 153 176 ...
##   ..$ bb     : num [1:1000] 780 773 766 760 792 781 755 770 797 774 ...
##   ..$ cb     : num [1:1000] 178 170 180 202 137 153 210 177 145 171 ...
##   ..$ db     : num [1:1000] 809 817 807 785 850 834 777 810 842 816 ...
##   ..$ corr_RR: num [1:1000] 0.995 1.049 1.038 0.985 1.11 ...
##   ..$ corr_OR: num [1:1000] 0.991 1.1 1.077 0.972 1.238 ...
##   ..$ rr_se_b: num [1:1000] 0.0605 0.0586 0.0579 0.0581 0.0599 ...
##   ..$ or_se_b: num [1:1000] 0.118 0.119 0.116 0.113 0.127 ...
##   ..$ z      : num [1:1000] -0.405 -0.818 1.345 2.238 1.091 ...
##   ..$ tot_RR : num [1:1000] 1.02 1.101 0.96 0.865 1.04 ...
##   ..$ tot_OR : num [1:1000] 1.039 1.213 0.921 0.754 1.078 ...
##   ..$ syst_RR: num [1:1000] 1.03 1.05 1.03 1.02 1.15 ...
##   ..$ syst_OR: num [1:1000] 1.06 1.09 1.05 1.04 1.35 ...
##  $ reps        : num 1000
##  $ fun         : chr &quot;probsens&quot;
##  $ warnings    : NULL
##  - attr(*, &quot;class&quot;)= chr [1:3] &quot;episensr&quot; &quot;episensr.probsens&quot; &quot;list&quot;</code></pre>
<p>Each of the lines from <code>mod1$sim_df[, 5:8]</code> can then be
tabulated and fed to the next bias function. Be careful, as the number
of observations can quickly become unmanageable.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="fu">head</span>(mod1<span class="sc">$</span>sim_df[, <span class="dv">5</span><span class="sc">:</span><span class="dv">8</span>])</span></code></pre></div>
<pre><code>##         A1       B1       C1       D1
## 1 156.8580 793.1420 155.7892 831.2108
## 2 174.2493 775.7507 168.3679 818.6321
## 3 197.1024 752.8976 196.5320 790.4680
## 4 192.4206 757.5794 193.0553 793.9447
## 5 157.2871 792.7129 126.7854 860.2146
## 6 174.1386 775.8614 142.1461 844.8539</code></pre>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
